language: python
python:
  - 3.6

services:
  - docker

install:
  - docker build -t max-nucleus-segmenter .
  - docker run -it -d -p 5050:5050 max-nucleus-segmenter
  - pip install -r requirements-test.txt

before_script:
  - flake8 . --max-line-length=127
  - bandit -r .
  - sleep 45

script:
  - pytest tests/test.py
