apiVersion: v1
kind: Service
metadata:
  name: max-nucleus-segmenter
spec:
  selector:
    app: max-nucleus-segmenter
  ports:
  - port: 5000
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: max-nucleus-segmenter
  labels:
    app: max-nucleus-segmenter
spec:
  selector:
    matchLabels:
      app: max-nucleus-segmenter
  replicas: 1
  template:
    metadata:
      labels:
        app: max-nucleus-segmenter
    spec:
      containers:
      - name: max-nucleus-segmenter
        image: quay.io/codait/max-nucleus-segmenter:latest
        ports:
        - containerPort: 5000